API_BASE_URL: https://api.groq.com/openai/v1/
INTERNET_ACCESS: true
MAX_SEARCH_RESULTS: 4

ALLOW_DM: true
SMART_MENTION: true

MODEL_ID: mixtral-8x7b-32768

MAX_HISTORY: 8

PRESENCES_CHANGE_DELAY: 8
AI_NSFW_CONTENT_FILTER: false

LANGUAGE: en

DEFAULT_INSTRUCTION: assist

Discord: https://discord.gg/6MT3CZauT8

TRIGGER:
  - chatbot
  - bot nickname
  - bot alias
  - bot name
  - Other bot alias...

AUTO_SHARDING: true

DISABLE_PRESENCE: false
PRESENCES:
  - How can I assist you?
  - Currently in {guild_count} guilds
  - Support at https://discord.gg/6MT3CZauT8

BLACKLIST_WORDS:
  - naked
  - loli
  - hentai
  - explicit
  - pornography
  - adult
  - XXX
  - sex
  - erotic

